# config/packages/security.yaml
security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: id

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        webhook:
            pattern: ^/webhook
            security: false

        passkey:
            pattern: ^/api/passkey
            security: false

        well_known:
            pattern: ^/\.well-known
            security: false

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/passkey, roles: PUBLIC_ACCESS }
        - { path: ^/api/legal, roles: PUBLIC_ACCESS }
        - { path: ^/webhook, roles: PUBLIC_ACCESS }
        - { path: ^/\.well-known, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
