apiVersion: v1
kind: ConfigMap
metadata:
  name: eupay-config
  namespace: eupay
data:
  APP_ENV: "prod"
  APP_DEBUG: "0"
  JWT_TOKEN_TTL: "3600"
  HCE_SESSION_KEY_TTL: "300"
  DATA_RETENTION_YEARS: "5"
  PRIVACY_POLICY_VERSION: "1.0.0"
  PSD2_API_BASE_URL: "https://api-sandbox.rabobank.nl"
  CARD_ISSUER_API_URL: "https://sandbox-api.marqeta.com"
  CORS_ALLOW_ORIGIN: "^https://app\\.eupay\\.eu$"

  # PHP-FPM tuning
  PHP_FPM_PM: "dynamic"
  PHP_FPM_MAX_CHILDREN: "50"
  PHP_FPM_START_SERVERS: "5"
  PHP_FPM_MIN_SPARE: "5"
  PHP_FPM_MAX_SPARE: "35"

  # Nginx
  NGINX_WORKER_PROCESSES: "auto"
  NGINX_WORKER_CONNECTIONS: "1024"
