apiVersion: v1
kind: Service
metadata:
  name: eupay-postgres
  namespace: eupay
  labels:
    app: eupay-postgres
spec:
  selector:
    app: eupay-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  clusterIP: None  # headless for StatefulSet
